/**
 * Auto-Chapters Service
 * Automatically detect scene changes and create video chapters
 */

class AutoChaptersService {
  constructor() {
    this.chapters = [];
    this.sceneThreshold = 30; // Difference threshold for scene detection
    this.minimumChapterDuration = 5; // Minimum 5 seconds per chapter
  }

  /**
   * Detect scene changes using frame difference analysis
   */
  async detectSceneChanges(videoElement, options = {}) {
    const {
      sampleRate = 1, // Sample every N seconds
      threshold = this.sceneThreshold,
      minDuration = this.minimumChapterDuration,
      onProgress = null
    } = options;

    return new Promise((resolve, reject) => {
      try {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d', { willReadFrequently: true });
        
        canvas.width = 160; // Low resolution for faster processing
        canvas.height = 90;

        const scenes = [];
        let previousFrame = null;
        let currentTime = 0;
        const duration = videoElement.duration;

        const processFrame = () => {
          if (currentTime >= duration) {
            // Process complete
            const chapters = this.createChaptersFromScenes(scenes, duration, minDuration);
            resolve(chapters);
            return;
          }

          videoElement.currentTime = currentTime;
        };

        videoElement.onseeked = () => {
          // Draw current frame
          ctx.drawImage(videoElement, 0, 0, canvas.width, canvas.height);
          const currentFrame = ctx.getImageData(0, 0, canvas.width, canvas.height);

          if (previousFrame) {
            // Calculate frame difference
            const difference = this.calculateFrameDifference(previousFrame, currentFrame);

            if (difference > threshold) {
              scenes.push({
                time: currentTime,
                difference: difference
              });
            }
          }

          previousFrame = currentFrame;
          currentTime += sampleRate;

          // Report progress
          if (onProgress) {
            onProgress({
              progress: (currentTime / duration) * 100,
              currentTime,
              duration,
              scenesDetected: scenes.length
            });
          }

          processFrame();
        };

        videoElement.onerror = (error) => {
          reject(error);
        };

        processFrame();

      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Calculate difference between two frames
   */
  calculateFrameDifference(frame1, frame2) {
    const data1 = frame1.data;
    const data2 = frame2.data;
    let totalDiff = 0;
    const pixels = data1.length / 4;

    for (let i = 0; i < data1.length; i += 4) {
      const rDiff = Math.abs(data1[i] - data2[i]);
      const gDiff = Math.abs(data1[i + 1] - data2[i + 1]);
      const bDiff = Math.abs(data1[i + 2] - data2[i + 2]);
      
      totalDiff += (rDiff + gDiff + bDiff) / 3;
    }

    return (totalDiff / pixels);
  }

  /**
   * Create chapters from detected scenes
   */
  createChaptersFromScenes(scenes, duration, minDuration) {
    const chapters = [];
    
    // Always start with chapter at 0
    let lastChapterTime = 0;

    scenes.forEach((scene, index) => {
      // Only create chapter if minimum duration has passed
      if (scene.time - lastChapterTime >= minDuration) {
        chapters.push({
          time: scene.time,
          title: `Chapter ${chapters.length + 1}`,
          autoGenerated: true,
          sceneChange: true,
          difference: scene.difference
        });
        lastChapterTime = scene.time;
      }
    });

    // Always add final chapter if needed
    if (duration - lastChapterTime >= minDuration) {
      chapters.push({
        time: lastChapterTime,
        title: `Chapter ${chapters.length + 1}`,
        autoGenerated: true,
        sceneChange: false
      });
    }

    return chapters;
  }

  /**
   * Detect chapters based on audio silence
   */
  async detectChaptersFromAudio(videoElement, options = {}) {
    const {
      silenceThreshold = -50, // dB
      minimumSilenceDuration = 1, // seconds
      minChapterDuration = this.minimumChapterDuration,
      onProgress = null
    } = options;

    return new Promise((resolve, reject) => {
      try {
        const audioContext = new AudioContext();
        const source = audioContext.createMediaElementSource(videoElement);
        const analyser = audioContext.createAnalyser();
        
        analyser.fftSize = 2048;
        source.connect(analyser);
        analyser.connect(audioContext.destination);

        const bufferLength = analyser.frequencyBinCount;
        const dataArray = new Uint8Array(bufferLength);

        const silences = [];
        let silenceStart = null;
        let currentTime = 0;
        const duration = videoElement.duration;

        const checkAudioLevel = () => {
          if (currentTime >= duration) {
            audioContext.close();
            const chapters = this.createChaptersFromSilences(silences, duration, minChapterDuration);
            resolve(chapters);
            return;
          }

          analyser.getByteFrequencyData(dataArray);
          const average = dataArray.reduce((a, b) => a + b) / bufferLength;
          const dB = 20 * Math.log10(average / 255);

          if (dB < silenceThreshold) {
            if (silenceStart === null) {
              silenceStart = currentTime;
            }
          } else {
            if (silenceStart !== null) {
              const silenceDuration = currentTime - silenceStart;
              if (silenceDuration >= minimumSilenceDuration) {
                silences.push({
                  start: silenceStart,
                  end: currentTime,
                  duration: silenceDuration
                });
              }
              silenceStart = null;
            }
          }

          if (onProgress) {
            onProgress({
              progress: (currentTime / duration) * 100,
              currentTime,
              duration,
              silencesDetected: silences.length
            });
          }

          currentTime += 0.1;
          videoElement.currentTime = currentTime;
          
          requestAnimationFrame(checkAudioLevel);
        };

        videoElement.play();
        checkAudioLevel();

      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Create chapters from silence periods
   */
  createChaptersFromSilences(silences, duration, minDuration) {
    const chapters = [];
    let lastChapterTime = 0;

    silences.forEach((silence) => {
      const chapterTime = silence.end;
      
      if (chapterTime - lastChapterTime >= minDuration) {
        chapters.push({
          time: chapterTime,
          title: `Chapter ${chapters.length + 1}`,
          autoGenerated: true,
          fromSilence: true,
          silenceDuration: silence.duration
        });
        lastChapterTime = chapterTime;
      }
    });

    return chapters;
  }

  /**
   * Combine scene and audio analysis for better chapters
   */
  async detectChaptersSmart(videoElement, options = {}) {
    try {
      const sceneChapters = await this.detectSceneChanges(videoElement, {
        ...options,
        onProgress: (progress) => {
          if (options.onProgress) {
            options.onProgress({ ...progress, phase: 'scene', step: 1, totalSteps: 2 });
          }
        }
      });

      const audioChapters = await this.detectChaptersFromAudio(videoElement, {
        ...options,
        onProgress: (progress) => {
          if (options.onProgress) {
            options.onProgress({ ...progress, phase: 'audio', step: 2, totalSteps: 2 });
          }
        }
      });

      // Merge and deduplicate chapters
      return this.mergeChapters(sceneChapters, audioChapters, options.minDuration || 5);

    } catch (error) {
      console.error('Smart chapter detection failed:', error);
      throw error;
    }
  }

  /**
   * Merge chapters from different sources
   */
  mergeChapters(chapters1, chapters2, minDuration = 5) {
    const allChapters = [...chapters1, ...chapters2];
    
    // Sort by time
    allChapters.sort((a, b) => a.time - b.time);

    // Remove duplicates (chapters within 2 seconds of each other)
    const merged = [];
    let lastTime = -10;

    allChapters.forEach(chapter => {
      if (chapter.time - lastTime >= minDuration) {
        merged.push(chapter);
        lastTime = chapter.time;
      }
    });

    // Renumber chapters
    return merged.map((chapter, index) => ({
      ...chapter,
      title: `Chapter ${index + 1}`,
      index: index + 1
    }));
  }

  /**
   * Export chapters as JSON
   */
  exportAsJSON(chapters) {
    return JSON.stringify({
      chapters,
      totalChapters: chapters.length,
      generatedAt: new Date().toISOString()
    }, null, 2);
  }

  /**
   * Export chapters for YouTube description
   */
  exportForYouTube(chapters) {
    return chapters.map(chapter => {
      const time = this.formatTime(chapter.time);
      return `${time} - ${chapter.title}`;
    }).join('\n');
  }

  /**
   * Format time as MM:SS or HH:MM:SS
   */
  formatTime(seconds) {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = Math.floor(seconds % 60);

    if (hours > 0) {
      return `${hours}:${String(minutes).padStart(2, '0')}:${String(secs).padStart(2, '0')}`;
    }
    return `${minutes}:${String(secs).padStart(2, '0')}`;
  }

  /**
   * Add custom chapter
   */
  addChapter(time, title, chapters = this.chapters) {
    const newChapter = {
      time,
      title,
      autoGenerated: false,
      custom: true
    };

    chapters.push(newChapter);
    chapters.sort((a, b) => a.time - b.time);

    // Renumber
    return chapters.map((chapter, index) => ({
      ...chapter,
      index: index + 1
    }));
  }

  /**
   * Remove chapter
   */
  removeChapter(index, chapters = this.chapters) {
    chapters.splice(index, 1);
    
    return chapters.map((chapter, idx) => ({
      ...chapter,
      index: idx + 1,
      title: chapter.custom ? chapter.title : `Chapter ${idx + 1}`
    }));
  }

  /**
   * Update chapter title
   */
  updateChapterTitle(index, newTitle, chapters = this.chapters) {
    if (chapters[index]) {
      chapters[index].title = newTitle;
      chapters[index].custom = true;
    }
    return chapters;
  }
}

// Singleton instance
let autoChaptersService = null;

/**
 * Get auto-chapters service instance
 */
export function getAutoChaptersService() {
  if (!autoChaptersService) {
    autoChaptersService = new AutoChaptersService();
  }
  return autoChaptersService;
}

/**
 * Quick chapter detection
 */
export async function detectChapters(videoElement, options = {}) {
  const service = getAutoChaptersService();
  return await service.detectChaptersSmart(videoElement, options);
}

export default AutoChaptersService;
